### ISSUE TITLE
Add pull request template 

### ISSUE THREAD

**Issue by jbampton** [SalamLang/Salam#100]

**Comment by anwarhossain1** [comment]
I want to work on this.

**Comment by jbampton** [comment]
Thanks @anwarhossain1 you are assigned now

**Comment by anwarhossain1** [comment]
Worked on this and gave a pull request.

**Comment by erfangnu** [comment]
Thanks mate, @jbampton please speed up review and merging process. We need to progress faster.

**Comment by erfangnu** [comment]
any updates?

**Comment by jbampton** [comment]
Done thanks !

**Comment by anwarhossain1** [comment]
You are welcome.
