### ISSUE TITLE
We need makefile to build and create production release (not dev)

### ISSUE THREAD

**Issue by erfangnu** [SalamLang/Salam#144]
We need makefile to build and create production release (not dev)

GNUMakefile is for linux
BSDMakefile is for bsd

can read more: https://alfonsosiciliano.gitlab.io/posts/2017-01-28-gnu-make-vs-bsd-make.html

**Comment by erfangnu** [comment]
production release = delete unused links, without memory debugger, without gcc debugger

**Comment by BaseMax** [comment]
I created it, looks fine for me.

we need to test, I close it for now.
