### ISSUE TITLE
Is this file extension correct: `examples/factorial-loop.salam.out.salam` ??

### ISSUE THREAD

**Issue by jbampton** [SalamLang/Salam#174]

**Comment by erfangnu** [comment]
no but i added ".out.salam" or ".salam.out" files to keep it ready for automated tests.

we need to change ".salam.out.salam" to ".salam.out"

**Comment by erfangnu** [comment]
fixed https://github.com/SalamLang/Salam/blob/main/examples/factorial-loop.salam.out

**Comment by jbampton** [comment]
Thanks

**Comment by erfangnu** [comment]
thank you for mentioning the issue.
we need more your help mate.
