### ISSUE TITLE
We need some linter/formatter/cleaner/checker for C in pre-commit or git hooks or thirdpart layer

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam#209]
https://github.com/dawnbeen/c_formatter_42

https://github.com/rishirdua/awesome-code-formatters?tab=readme-ov-file#cc

**Comment by BaseMax** [comment]
and https://interrupt.memfault.com/blog/pre-commit

**Comment by BaseMax** [comment]
That’s what formatting tools can do. For the C language, some popular formatters are:

[clang-format](https://releases.llvm.org/15.0.0/tools/clang/docs/ClangFormat.html)
[uncrustify](http://uncrustify.sourceforge.net/)
[GNU Indent](https://www.gnu.org/software/indent/)
[Astyle](http://astyle.sourceforge.net/)

**Comment by BDadmehr0** [comment]
I have worked on this issue. You can view it at this link: 'https://github.com/SalamLang/Salam/pull/219/'

**Comment by BaseMax** [comment]
Thanks @BDadmehr0 
done
