### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by BDadmehr0** [SalamLang/Salam#241]
I make the program executable and run it, but I encounter the following error:

``` bash
➜  Downloads file salam-linux; chmod +x salam-linux               
salam-linux: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=dd892c221cd037eb551bd593d31cb6ca1d7c32f4, for GNU/Linux 3.2.0, with debug_info, not stripped
➜  Downloads ./salam-linux       
./salam-linux: error while loading shared libraries: libasan.so.6: cannot open shared object file: No such file or directory

```

**Expected behavior**
The program's output must be like the output of README.md.

```
$ ./salam
Welcome to Salam Programming Language!
Salam is the first Persian/Iranian computer scripting language.

Usage:
./salam <filename>                      # Execute a Salam script
./salam code <content> <output_dir>     # Compile and run Salam code

./salam lint <filename> <output_dir>    # Lint a Salam script
./salam lint code <content>             # Lint Salam code

./salam version                         # Print the version of Salam

./salam update                          # Update Salam to the latest version

Feel free to explore and create using Salam!
For more information, visit: https://salamlang.ir
```

**Desktop (please complete the following information):**

- OS: Arch Linux x86_64
- Kernel: 6.11.3-arch1-1
- Browser Firefox

**Comment by BaseMax** [comment]
Hi @BDadmehr0 
Thank you so much.

The error message error while loading shared libraries: libasan.so.6: cannot open shared object file: No such file or directory indicates that the program is trying to use the libasan.so.6 library, which is part of the AddressSanitizer (ASan) tool for detecting memory-related issues. However, this library is missing on your system.

We are using that library for debug mode, if you want to stay on debug you need to install libasan by `pacman` the package manager in Arch. (I am an ARCH lover like you)

If not, let's build in production mode.

---


In addition to the above, I made some new updates to make it easier.

For debug mode: `make debug`

For production mode: `make`

**Comment by BDadmehr0** [comment]
Hi,  
I initially updated the repository and installed all prerequisites as suggested. However, when running `make`, I encountered errors related to the absence of `pre-commit` and issues with the `PATH` configuration. Here’s how I resolved it:

1. **Installing `pre-commit`**: Since I’m on Arch Linux, I had to install `pre-commit` using the following command due to the system’s package management restrictions:

   ```bash
   pip install pre-commit --break-system-packages
   ```

2. **Adding `~/.local/bin` to `PATH`**: After installation, I added `~/.local/bin` to my `PATH` so the system could locate `pre-commit`:

   ```bash
   echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.zshrc
   source ~/.zshrc
   ```

3. **Verifying `pre-commit`**: I confirmed the installation by running:

   ```bash
   pre-commit --version
   ```

4. **Successful `make` Execution**: Finally, I re-ran `make` without any issues, and the project built successfully.

---

This should help others facing similar issues with running `make` : 

```  bash
➜  Salam git:(main) make
pre-commit install
pre-commit installed at .git/hooks/pre-commit
pre-commit run --all-files
[INFO] Initializing environment for local:prettier@3.3.3.
[INFO] Initializing environment for https://github.com/psf/black-pre-commit-mirror.
[INFO] Initializing environment for https://github.com/PyCQA/bandit.
[INFO] Initializing environment for https://github.com/gitleaks/gitleaks.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/codespell-project/codespell.
[INFO] Initializing environment for https://github.com/tcort/markdown-link-check.
[INFO] Initializing environment for https://github.com/igorshubovych/markdownlint-cli.
[INFO] Initializing environment for https://github.com/shssoichiro/oxipng.
[INFO] Initializing environment for https://github.com/adrienverge/yamllint.
[WARNING] Unexpected key(s) present on https://github.com/adrienverge/yamllint => yamllint: env
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-clang-format.
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
```

**Comment by BaseMax** [comment]
@BDadmehr0 thanks. So it's finally solved and you managed to run **Salam** compiler?

@jbampton Why should we run Pre-Commit in the build process? It is better to call running pre-commit in the git push/git commit phase. Not running making/building!

**Comment by BDadmehr0** [comment]
> @BDadmehr0 thanks. So it's finally solved and you managed to run **Salam** compiler?

No, it still didn't work. I followed all the steps you mentioned, but it gets stuck at the final step:

```bash
➜  Salam git:(main) ✗ git pull
Already up to date.
➜  Salam git:(main) ✗ make debug
make: *** No rule to make target 'debug'.  Stop.
➜  Salam git:(main) ✗ make 
pre-commit install
pre-commit installed at .git/hooks/pre-commit
pre-commit run --all-files
[INFO] Locking pre-commit directory
```

It seems there's no rule for `debug` in the `Makefile`, and it stops there.

**Comment by jbampton** [comment]
Hey @BDadmehr0 we have a second Makefile here:

https://github.com/SalamLang/Salam/blob/main/src/Makefile

**Comment by BDadmehr0** [comment]
I went back to the previous method, executed the file, and the expected output was displayed:

```
➜  Downloads chmod +x salam-linux 
➜  Downloads ./salam-linux 
Welcome to Salam Programming Language!
Salam is the first Persian/Iranian computer scripting language.

Usage:
./salam-linux <filename>                      # Execute a Salam script
./salam-linux code <content> <output_dir>     # Compile and run Salam code

./salam-linux lint <filename> <output_dir>    # Lint a Salam script
./salam-linux lint code <content>             # Lint Salam code

./salam-linux version                         # Print the version of Salam

./salam-linux update                          # Update Salam to the latest version

Feel free to explore and create using Salam!

For more information, visit: https://salamlang.ir

```

**Comment by BDadmehr0** [comment]
> Hey @BDadmehr0 we have a second Makefile here:
> 
> https://github.com/SalamLang/Salam/blob/main/src/Makefile

It worked.

**Comment by BaseMax** [comment]
Good. happy to hear it. what was the problem or mistake?

**Comment by BaseMax** [comment]
```
صفحه:
     محتوا = "سلام دنیا"
تمام
```

or

```
صفحه:
    ضخیم:
        محتوا = «سلام دنیا»
    تمام
تمام
```

**Comment by BaseMax** [comment]
You can also write online codes here. https://editor.salamlang.ir/

**Comment by jbampton** [comment]
> Good. happy to hear it. what was the problem or mistake?

We have two different Makefiles.  

@BDadmehr0 ran the wrong Makefile first time

**Comment by BaseMax** [comment]
> We have two different Makefiles.

Aha, let's combine in a generic Makefile, we can add pre-commit as an optional parameter to the main "Makefile".

https://github.com/SalamLang/Salam/blob/main/Makefile

**Comment by BaseMax** [comment]
Are we using the Makefile inside the root somewhere in GitHub actions or hooks? @jbampton

**Comment by jbampton** [comment]
I was just using the root Makefile for convenience since it has the most important commands to install and run pre-commit

**Comment by BDadmehr0** [comment]
Can I close this issue?

**Comment by BaseMax** [comment]
Sure, feel free.
Thanks
