### ISSUE TITLE
We should add the `Hound` 

### ISSUE THREAD

**Issue by jbampton** [SalamLang/Salam#286]
https://houndci.com/

I've used it before on another repo.

Barks at contributors that don't follow common coding conventions etc.

https://houndci.com/#pricing

Hound is free for public repos!

**Comment by BDadmehr0** [comment]
Hello, I requested to be added to the [houndci](https://houndci.com/).

**Comment by BaseMax** [comment]
@jbampton please check.

**Comment by jbampton** [comment]
Hound is now added on this repo.

Thanks everyone :+1:
