### ISSUE TITLE
Add the pull request labeler

### ISSUE THREAD

**Issue by jbampton** [SalamLang/Salam#29]

**Comment by anufdo** [comment]
@jbampton, Could you please assign this task to me

**Comment by jbampton** [comment]
Thanks @anufdo

**Comment by erfangnu** [comment]
a reminder @anufdo

**Comment by anufdo** [comment]
@erfangnu Hi, I've completed the task. It's under review: https://github.com/SalamLang/Salam/pull/133

**Comment by jbampton** [comment]
https://github.com/SalamLang/Salam/actions/runs/9233701149/job/25406452407?pr=113

**Comment by jbampton** [comment]
Thanks

**Comment by erfangnu** [comment]
thanks all
