### ISSUE TITLE
Request to add "Hound" app on repository

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam#306]
![image](https://github.com/user-attachments/assets/9df3c647-ddef-4d1b-aced-b4224dcae4b1)

Done:
![image](https://github.com/user-attachments/assets/7feda3e8-3a59-4c33-a5f3-a2afe3576b0e)

**Comment by BaseMax** [comment]
cc @bdadmehr0

**Comment by jbampton** [comment]
https://github.com/SalamLang/Salam/issues/286

@BaseMax

**Comment by BaseMax** [comment]
Okay so already added. let's close it
