### ISSUE TITLE
 How to make a page that displays a text in the center - نحوه ساخت یک صفحه که یک متن را در مرکز ان نمایش دهد

### ISSUE THREAD

**Issue by MAGNET-CODE** [SalamLang/Salam#339]

**Comment by jbampton** [comment]
نحوه ساخت یک صفحه که یک متن را در مرکز ان نمایش دهد

Google translate of Persian ?? into English is:

`How to make a page that displays a text in the center`

**Comment by BDadmehr0** [comment]
I reviewed the [documents](https://docs.salamlang.ir/) once again, and there is no title referring to this museum. @jbampton @BaseMax

**Comment by BaseMax** [comment]
Feel free to try it https://editor.salamlang.ir/

```
صفحه:
     عنوان = «عنوان این صفحه»
     توضیح = «متن توضیح صفحه»
     نویسنده = «نام نویسنده و طراح»

     رنگ پس زمینه = «سیاه»
     رنگ = «سفید»
     تراز متن = «مرکز»

     قطعه:
               اندازه قلم = ۵۰
               محتوا = «سلام دنیا»
               رنگ پس زمینه = «قرمز»
               گردی = ۹
               فاصله = ۸
             
     تمام

تمام
```

![image](https://github.com/user-attachments/assets/f12de88f-e1be-48c4-9f63-d0ea28918557)

**Comment by BaseMax** [comment]
Many thanks for asking questions. @MAGNET-CODE

**Comment by jbampton** [comment]
> I reviewed the [documents](https://docs.salamlang.ir/) once again, and there is no title referring to this museum. @jbampton @BaseMax

Do we need an example for this ?

https://github.com/SalamLang/Salam/tree/main/example

**Comment by BDadmehr0** [comment]
I thought it would be necessary because it was strange to me since I was looking for the side(top, both, ...) attribute in the text options. When I encountered the [examples](https://github.com/SalamLang/Salam/issues/339#issuecomment-2498895170) above, I was surprised because the method above creates a button.

And if the answer is [this](https://github.com/SalamLang/Salam/issues/339#issuecomment-2498895170), there's no need to add an extra example.

@jbampton

**Comment by BaseMax** [comment]
قطعه tag is like span tag.
If you need a real button, you can use `دکمه` element.


```
دکمه:
    محتوا = «متن دکمه»
    رنگ = «قرمز»
   رنگ پس زمینه = «زرد»
    فاصله = ۲۰
     گردی = ۹
 تمام
```

**Comment by BDadmehr0** [comment]
> قطعه tag is like span tag.
> If you need a real button, you can use `دکمه` element.
> 
> 
> ```
> دکمه:
>     محتوا = «متن دکمه»
>     رنگ = «قرمز»
>    رنگ پس زمینه = «زرد»
>     فاصله = ۲۰
>      گردی = ۹
>  تمام
> ```

Generally, there is no need for a button when we want to display text in the center of the page. It is expected that we look for a part of the text that determines where the text should be placed, not a button.

**Comment by BaseMax** [comment]
That's right, I just used a few useful and popular features and elements to display the page.

A simple solution is:

```
صفحه:
    محتوا = "محل متن"
    ...
تمام
```
