### ISSUE TITLE
اگر به پایتون علاقه دارید می توانید روی اسکریپت های پایتون کار کنید. کد های اونها خوب نیست و توابع داره به شدت داخل فایل ها تکرار میشه. باید یک ماژول بسازیم و توابع رو به فایل های دیگر منتقل کنیم تا تمیز بشود.

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam#346]

**Comment by BDadmehr0** [comment]
سلام, آیا توابع خاصی مد نظر دارید ؟
من فایل ها را جک کردم و توابع که اکثرا تکرار میشه : [تابع error](https://github.com/SalamLang/Salam/blob/main/config/type.validate.py#L11) - [تابع command](https://github.com/SalamLang/Salam/blob/main/config/sync.py#L84) دو بار تکرار میشود.
اگر مایل باشید در همان دایرکتوری config برای این توابع یک ماژول ساخته و از ان ماژول در کد ها استفاده میکنم
@BaseMax

**Comment by BaseMax** [comment]
سلام
بله موافق هستم یک ماژ>ل در همان پوشه کانفیگ ساخته شود و تمیزکاری انجام شود.
هر انچه که دارد تکرار می شود به ماژول منتقل شود و در ساب پوشه های داخل کانفیگ از ان ماژول ساتفاده شود.

ارادت

**Comment by BaseMax** [comment]
همین موضوع رو باید برای تمام validate scripts ها هم پیاده کنیم. مثلا language.validate.py

```
def error(msg: str) -> None:
    print("Error: " + msg)
    exit(1)

```

همینطور کد هایی که تکرار میشه مثل:
```
file = open(FILE, "r", encoding="utf-8")
docs = yaml.safe_load_all(file)

```
باید تابع بشوند.

**Comment by BaseMax** [comment]
اینکار در حال انجام هست؟ چقدر دیگه کار داره؟

**Comment by BDadmehr0** [comment]
> اینکار در حال انجام هست؟ چقدر دیگه کار داره؟

سلام، ینده به شدت مشغول هستم اما در اسرع وقت به آن رسیدگی میکنم

**Comment by BDadmehr0** [comment]
close? @BaseMax

**Comment by BaseMax** [comment]
Many thanks

**Comment by BaseMax** [comment]
Thank you! It’s all good; I worked on it today, and it’s functioning fine. I’ve added an admin panel located in `config/admin/`. You might want to review it and consider improving my code.

Best regards,
Max

**Comment by BDadmehr0** [comment]
یک پیشنهاد دیگر، من وقتی داشتم کد ها برسی میکردم برای هر فایل yaml یک کد نوشته شده بود که برسی میکرد فایل رو، به جای این می‌توان کاری کرد که با یک فایل پایتونی چندین yaml رو برسی کرد.

خوش حال میشم نظرتون رو درمورد این بدونم @BaseMax

**Comment by BaseMax** [comment]
مسعله این هست که هر فایل yaml بصورت مختلفی چک میشه مثلا هر کدوم یکسری فیلد های اجباری و اختیاری متفاوتی دارند.
اگه یک ساختار داخل کتابخانه پیاده بشه که بشه به تابع مقادیر اختیاری و اجباری رو پاس داد و حتی یک کاستوم فانکشن بهش پاس داد برای موارد خیلی خاص و ریز اینطوری دیگه میشه همه رو یکی کرد.

**Comment by BaseMax** [comment]
این پیام رو در پاسخ با ایمیل که دریافت کرده بودم نوشتم:

```
یک پیشنهاد دیگر، من وقتی داشتم کد ها برسی میکردم برای هر فایل yaml یک کد نوشته شده بود که برسی میکرد فایل رو، به جای این می‌توان کاری کرد که با یک فایل پایتونی چندین yaml رو برسی کرد.

خوش حال میشم نظرتون رو درمورد این بدونم [@BaseMax](https://github.com/BaseMax)
```

**Comment by BDadmehr0** [comment]
بله متوجه هستم اولش فکر کردم در ایوشز اشتباهی این پیام رو نشوتم و پاک کردم و دیگه نخواستم دوباره بنویسم. من رو این مورد هم کار میکنم و اگه بشه اراعه میدم

> این پیام رو در پاسخ با ایمیل که دریافت کرده بودم نوشتم:
> 
> ```
> یک پیشنهاد دیگر، من وقتی داشتم کد ها برسی میکردم برای هر فایل yaml یک کد نوشته شده بود که برسی میکرد فایل رو، به جای این می‌توان کاری کرد که با یک فایل پایتونی چندین yaml رو برسی کرد.
> 
> خوش حال میشم نظرتون رو درمورد این بدونم [@BaseMax](https://github.com/BaseMax)
> ```

**Comment by BaseMax** [comment]
Many thanks
