### ISSUE TITLE
for(برای) -> attr

### ISSUE THREAD

**Issue by mohamadreza1388** [SalamLang/Salam#364]
صفت 'برای' که مربوط به برچسب است کار نمیکند
مثال 
```
صفحه:
	برچسب:
		محتوا = «نام»	
		برای=«input»
	تمام

	ورودی:
		شناسه=«input»
	تمام 
تمام
```

**Comment by BaseMax** [comment]
حل شد. سپاس
https://github.com/SalamLang/Salam/commit/d12a0a917f8b1f01b78d3f27930dc9def6130c52
