### ISSUE TITLE
Add `prettier` with `pre-commit`

### ISSUE THREAD

**Issue by jbampton** [SalamLang/Salam#37]

**Comment by erfangnu** [comment]
a reminder

**Comment by erfangnu** [comment]
we need your help @jbampton

**Comment by erfangnu** [comment]
@jbampton make it faster

**Comment by jbampton** [comment]
This repository has been archived by the owner on Apr 12, 2024. It is now read-only.

https://github.com/pre-commit/mirrors-prettier

**Comment by erfangnu** [comment]
thanks mate
