### ISSUE TITLE
command() in the sync py script is broken, it seems like all the different commands() have been removed and converted to a common command() which is wrong

### ISSUE THREAD

**Issue by BaseMax** [SalamLang/Salam#373]
command() in the sync py script is broken, it seems like all the different commands() have been removed and converted to a common command() which is wrong

**Comment by BaseMax** [comment]
Based on https://github.com/SalamLang/Salam/blob/7d30760e3da2e4f7de5c7d2608f63b99f53505d3/config/sync.py we need 2 diffrent `command()` functions.

**Comment by BaseMax** [comment]
Fixed https://github.com/SalamLang/Salam/commit/48ddb4e4672e5184a2ee170c27382e573570f566

@BDadmehr0

**Comment by jbampton** [comment]
This file no longer exists in the new system. Closing as done. Thanks everyone
