### ISSUE TITLE
Add GitHub issue templates

### ISSUE THREAD

**Issue by jbampton** [SalamLang/Salam#44]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by anwarhossain1** [comment]
I want to fix it.

**Comment by jbampton** [comment]
You are now assigned @anwarhossain1 thanks

**Comment by anwarhossain1** [comment]
Should i close the pull request?
