### ISSUE TITLE
Add `ClangFormat` with `pre-commit`

### ISSUE THREAD

**Issue by jbampton** [SalamLang/Salam#46]
https://clang.llvm.org/docs/ClangFormat.html

**Comment by erfangnu** [comment]
we need your help @jbampton

**Comment by erfangnu** [comment]
@jbampton make it faster

**Comment by BaseMax** [comment]
Please check it mate @jbampton

**Comment by BaseMax** [comment]
Do we need it or not? @jbampton @BDadmehr0

**Comment by BDadmehr0** [comment]
> Do we need it or not? @jbampton @BDadmehr0

[Added clang-format to pre-commit](https://github.com/SalamLang/Salam/blob/main/.pre-commit-config.yaml[66]). I don't think it is needed anymore

**Comment by BaseMax** [comment]
@jbampton if you are okay please close this issue.

**Comment by jbampton** [comment]
Done now. Thanks !!

https://github.com/SalamLang/Salam/blob/a76114c780b6c96b184d584d9f1068baba2e53a3/.pre-commit-config.yaml#L70
